[package]
name = "hanzo-evm-static-file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Static file producer implementation"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-codecs.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-storage-errors.workspace = true
hanzo-evm-tokio-util.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-static-file-types.workspace = true
hanzo-evm-stages-types.workspace = true

alloy-primitives.workspace = true

# misc
tracing.workspace = true
rayon.workspace = true
parking_lot = { workspace = true, features = ["send_guard", "arc_lock"] }

[dev-dependencies]
hanzo-evm-stages = { workspace = true, features = ["test-utils"] }
hanzo-evm-testing-utils.workspace = true

assert_matches.workspace = true
tempfile.workspace = true

[features]
edge = ["hanzo-evm-stages/edge"]
