[package]
name = "hanzo-evm-rpc-eth-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM RPC 'eth' namespace API"

[lints]
workspace = true

[dependencies]
# evm
revm = { workspace = true, features = ["optional_block_gas_limit", "optional_eip3607", "optional_no_base_fee", "optional_fee_charge", "memory_limit"] }
hanzo-evm-chain-state.workspace = true
revm-inspectors.workspace = true
hanzo-evm-primitives-traits = { workspace = true, features = ["rpc-compat"] }
hanzo-evm-errors.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-revm.workspace = true
hanzo-evm-rpc-convert.workspace = true
hanzo-evm-tasks = { workspace = true, features = ["rayon"] }
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-rpc-eth-types.workspace = true
hanzo-evm-rpc-server-types.workspace = true
hanzo-evm-network-api.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-trie-common = { workspace = true, features = ["eip1186"] }

# ethereum
alloy-evm = { workspace = true, features = ["overrides", "call-util"] }
alloy-rlp.workspace = true
alloy-serde.workspace = true
alloy-eips.workspace = true
alloy-dyn-abi = { workspace = true, features = ["eip712"] }
alloy-json-rpc.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-consensus.workspace = true

# rpc
jsonrpsee = { workspace = true, features = ["server", "macros"] }
jsonrpsee-types.workspace = true

# async
async-trait.workspace = true
futures.workspace = true
parking_lot.workspace = true
tokio.workspace = true

# misc
auto_impl.workspace = true
dyn-clone.workspace = true
tracing.workspace = true

[features]
js-tracer = ["revm-inspectors/js-tracer", "hanzo-evm-rpc-eth-types/js-tracer"]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
op = [
    "hanzo-evm-execution/op",
    "hanzo-evm-primitives-traits/op",
    "hanzo-evm-rpc-convert/op",
    "alloy-evm/op",
]
