[package]
name = "hanzo-evm-network-p2p"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "traits and commonly used types for p2p and network communication"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-eth-wire-types.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-network-peers.workspace = true
hanzo-evm-network-types.workspace = true
hanzo-evm-storage-errors.workspace = true

# ethereum
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives = { workspace = true, features = ["rand"] }

# async
futures.workspace = true
tokio = { workspace = true, features = ["sync"] }

# misc
auto_impl.workspace = true
tracing.workspace = true
derive_more.workspace = true
parking_lot = { workspace = true, optional = true }

[dev-dependencies]
hanzo-evm-consensus = { workspace = true, features = ["test-utils"] }

parking_lot.workspace = true
tokio = { workspace = true, features = ["full"] }

[features]
default = ["std"]
test-utils = [
    "hanzo-evm-consensus/test-utils",
    "parking_lot",
    "hanzo-evm-network-types/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "alloy-primitives/rand",
]
std = [
    "hanzo-evm-consensus/std",
    "hanzo-evm-ethereum-primitives/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "hanzo-evm-primitives-traits/std",
    "alloy-consensus/std",
    "derive_more/std",
    "hanzo-evm-network-peers/std",
    "hanzo-evm-storage-errors/std",
    "tracing/std",
]
