[package]
name = "hanzo-evm-downloaders"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Implementations of various block downloaders"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-config.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-network-p2p.workspace = true
hanzo-evm-network-peers.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-tasks.workspace = true

# optional deps for the test-utils feature
hanzo-evm-ethereum-primitives = { workspace = true, optional = true }
hanzo-evm-provider = { workspace = true, optional = true }
hanzo-evm-testing-utils = { workspace = true, optional = true }

# ethereum
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rlp = { workspace = true, optional = true }

# async
futures.workspace = true
futures-util.workspace = true
pin-project.workspace = true
tokio = { workspace = true, features = ["sync", "fs", "io-util"] }
tokio-stream.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
async-compression = { workspace = true, features = ["gzip", "tokio"], optional = true }

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true

# misc
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true

tempfile = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }

[dev-dependencies]
async-compression = { workspace = true, features = ["gzip", "tokio"] }
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-consensus = { workspace = true, features = ["test-utils"] }
hanzo-evm-network-p2p = { workspace = true, features = ["test-utils"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-testing-utils.workspace = true
hanzo-evm-tracing.workspace = true

assert_matches.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
rand.workspace = true
tempfile.workspace = true
alloy-rlp.workspace = true
itertools.workspace = true

[features]
default = []
file-client = ["dep:async-compression", "dep:alloy-rlp", "dep:itertools"]
test-utils = [
    "tempfile",
    "hanzo-evm-consensus/test-utils",
    "hanzo-evm-network-p2p/test-utils",
    "hanzo-evm-testing-utils",
    "hanzo-evm-chainspec/test-utils",
    "hanzo-evm-provider/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "dep:hanzo-evm-ethereum-primitives",
    "hanzo-evm-ethereum-primitives?/test-utils",
]
