[package]
name = "hanzo-evm-node-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-basic-payload-builder.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-engine-primitives.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-payload-builder-primitives.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-network-api.workspace = true
hanzo-evm-node-types.workspace = true
hanzo-evm-node-core.workspace = true
hanzo-evm-tokio-util.workspace = true

alloy-rpc-types-engine.workspace = true

eyre.workspace = true
