[package]
name = "hanzo-evm-chain-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM state related types and functionality."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-chainspec.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-metrics.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-trie.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-primitives = { workspace = true, features = ["std"] }
alloy-consensus.workspace = true
revm-database.workspace = true
revm-state = { workspace = true, optional = true }

# async
tokio = { workspace = true, default-features = false, features = ["sync", "macros"] }
tokio-stream = { workspace = true, features = ["sync"] }

# tracing
tracing.workspace = true

# misc
derive_more.workspace = true
metrics.workspace = true
parking_lot.workspace = true
pin-project.workspace = true
rayon = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

# optional deps for test-utils
alloy-signer = { workspace = true, optional = true }
alloy-signer-local = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
hanzo-evm-primitives-traits = { workspace = true, features = ["test-utils"] }
hanzo-evm-testing-utils.workspace = true
alloy-signer.workspace = true
alloy-signer-local.workspace = true
rand.workspace = true
revm-state.workspace = true
criterion.workspace = true

[features]
serde = [
    "dep:serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "parking_lot/serde",
    "rand?/serde",
    "hanzo-evm-ethereum-primitives/serde",
    "hanzo-evm-execution-types/serde",
    "hanzo-evm-primitives-traits/serde",
    "hanzo-evm-trie/serde",
    "revm-database/serde",
    "revm-state?/serde",
    "hanzo-evm-storage-api/serde",
]
test-utils = [
    "alloy-primitives/getrandom",
    "alloy-signer",
    "alloy-signer-local",
    "rand",
    "revm-state",
    "hanzo-evm-chainspec/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-trie/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
]
rayon = ["dep:rayon"]

[[bench]]
name = "canonical_hashes_range"
harness = false
required-features = ["test-utils"]
