[package]
name = "hanzo-evm-engine-tree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-chain-state = { workspace = true, features = ["rayon"] }
hanzo-evm-chainspec = { workspace = true, optional = true }
hanzo-evm-consensus.workspace = true
hanzo-evm-db.workspace = true
hanzo-evm-engine-primitives = { workspace = true, features = ["std"] }
hanzo-evm-errors.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-execution = { workspace = true, features = ["metrics"] }
hanzo-evm-network-p2p.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-primitives-traits = { workspace = true, features = ["rayon", "dashmap"] }
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-prune.workspace = true
hanzo-evm-revm = { workspace = true, features = ["optional-balance-check"] }
hanzo-evm-stages-api.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-trie-parallel.workspace = true
hanzo-evm-trie-sparse = { workspace = true, features = ["std", "metrics"] }
hanzo-evm-trie-sparse-parallel = { workspace = true, features = ["std"] }
hanzo-evm-trie.workspace = true
hanzo-evm-trie-common.workspace = true
hanzo-evm-trie-db.workspace = true

# alloy
alloy-evm.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-eip7928.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types-engine.workspace = true

revm.workspace = true
revm-primitives.workspace = true

# common
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync", "macros"] }
fixed-cache.workspace = true
moka = { workspace = true, features = ["sync"] }
smallvec.workspace = true

# metrics
metrics.workspace = true
hanzo-evm-metrics = { workspace = true, features = ["common"] }

# misc
schnellru.workspace = true
rayon.workspace = true
tracing.workspace = true
derive_more.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true

# optional deps for test-utils
hanzo-evm-prune-types = { workspace = true, optional = true }
hanzo-evm-stages = { workspace = true, optional = true }
hanzo-evm-static-file = { workspace = true, optional = true }
hanzo-evm-tracing = { workspace = true, optional = true }

[dev-dependencies]
# evm
hanzo-evm-eth-execution = { workspace = true, features = ["test-utils"] }
hanzo-evm-chain-state = { workspace = true, features = ["test-utils"] }
hanzo-evm-chainspec.workspace = true
hanzo-evm-db-common.workspace = true
hanzo-evm-ethereum-consensus.workspace = true
metrics-util = { workspace = true, features = ["debugging"] }
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-execution = { workspace = true, features = ["test-utils"] }
hanzo-evm-exex-types.workspace = true
hanzo-evm-network-p2p = { workspace = true, features = ["test-utils"] }
hanzo-evm-prune-types.workspace = true
hanzo-evm-stages = { workspace = true, features = ["test-utils"] }
hanzo-evm-static-file.workspace = true
hanzo-evm-testing-utils.workspace = true
hanzo-evm-tracing.workspace = true
hanzo-evm-node-ethereum.workspace = true
hanzo-evm-e2e-test-utils.workspace = true

# revm
revm-state.workspace = true

assert_matches.workspace = true
criterion.workspace = true
eyre.workspace = true
serde_json.workspace = true
crossbeam-channel.workspace = true
proptest.workspace = true
rand.workspace = true
rand_08.workspace = true

[[bench]]
name = "channel_perf"
harness = false

[[bench]]
name = "state_root_task"
harness = false

[features]
test-utils = [
    "hanzo-evm-chain-state/test-utils",
    "hanzo-evm-chainspec/test-utils",
    "hanzo-evm-consensus/test-utils",
    "hanzo-evm-db/test-utils",
    "hanzo-evm-execution/test-utils",
    "hanzo-evm-network-p2p/test-utils",
    "hanzo-evm-payload-builder/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-provider/test-utils",
    "hanzo-evm-prune-types",
    "hanzo-evm-prune-types?/test-utils",
    "hanzo-evm-revm/test-utils",
    "hanzo-evm-stages-api/test-utils",
    "hanzo-evm-stages/test-utils",
    "hanzo-evm-static-file",
    "hanzo-evm-tracing",
    "hanzo-evm-trie/test-utils",
    "hanzo-evm-trie-common/test-utils",
    "hanzo-evm-trie-db/test-utils",
    "hanzo-evm-trie-sparse/test-utils",
    "hanzo-evm-prune-types?/test-utils",
    "hanzo-evm-trie-parallel/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
    "hanzo-evm-node-ethereum/test-utils",
    "hanzo-evm-eth-execution/test-utils",
]

[[test]]
name = "e2e_testsuite"
path = "tests/e2e-testsuite/main.rs"
