[package]
name = "hanzo-evm-node-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-chainspec.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-engine-primitives.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-payload-primitives.workspace = true

[features]
default = ["std"]
std = [
    "hanzo-evm-primitives-traits/std",
    "hanzo-evm-chainspec/std",
    "hanzo-evm-engine-primitives/std",
]
