[package]
name = "hanzo-evm-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Database primitives used in Hanzo EVM."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-db-api.workspace = true
hanzo-evm-fs-util.workspace = true
hanzo-evm-storage-errors.workspace = true
hanzo-evm-nippy-jar.workspace = true
hanzo-evm-tracing.workspace = true
tracing.workspace = true
hanzo-evm-static-file-types.workspace = true

# ethereum
alloy-primitives.workspace = true

# mdbx
hanzo-evm-libmdbx = { workspace = true, optional = true, features = ["return-borrowed", "read-tx-timeouts"] }
eyre = { workspace = true, optional = true }

# metrics
hanzo-evm-metrics = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }

# misc
page_size = { workspace = true, optional = true }
thiserror.workspace = true
tempfile = { workspace = true, optional = true }
derive_more.workspace = true
rustc-hash = { workspace = true, optional = true, features = ["std"] }
sysinfo = { workspace = true, features = ["system"] }
parking_lot = { workspace = true, optional = true }

# arbitrary utils
strum = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
# evm libs with arbitrary
hanzo-evm-primitives-traits = { workspace = true, features = ["hanzo-evm-codec"] }
hanzo-evm-prune-types.workspace = true

alloy-primitives = { workspace = true, features = ["getrandom"] }
alloy-consensus.workspace = true

serde_json.workspace = true
tempfile.workspace = true
parking_lot.workspace = true

serde.workspace = true
criterion.workspace = true

arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true

assert_matches.workspace = true

[features]
default = ["mdbx"]
mdbx = [
    "dep:hanzo-evm-libmdbx",
    "dep:eyre",
    "dep:page_size",
    "hanzo-evm-metrics",
    "dep:metrics",
    "dep:strum",
    "dep:rustc-hash",
]
test-utils = [
    "dep:tempfile",
    "mdbx",
    "arbitrary",
    "parking_lot",
    "hanzo-evm-db-api/test-utils",
    "hanzo-evm-nippy-jar/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-prune-types/test-utils",
]
bench = ["hanzo-evm-db-api/bench"]
arbitrary = [
    "hanzo-evm-db-api/arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-consensus/arbitrary",
    "hanzo-evm-primitives-traits/arbitrary",
    "hanzo-evm-prune-types/arbitrary",
]
op = [
    "hanzo-evm-db-api/op",
    "hanzo-evm-primitives-traits/op",
]
disable-lock = []

[[bench]]
name = "hash_keys"
required-features = ["test-utils"]
harness = false

[[bench]]
name = "criterion"
required-features = ["test-utils"]
harness = false

[[bench]]
name = "get"
required-features = ["test-utils"]
harness = false

[[bench]]
name = "put"
required-features = ["test-utils"]
harness = false
