[package]
name = "hanzo-evm-ress-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-eth-wire.workspace = true
hanzo-evm-network-api.workspace = true
hanzo-evm-network.workspace = true
hanzo-evm-storage-errors.workspace = true
hanzo-evm-ethereum-primitives.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-consensus.workspace = true

# misc
futures.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
tracing.workspace = true

# feature `arbitrary`
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
hanzo-evm-eth-wire = { workspace = true, features = ["arbitrary"] }
hanzo-evm-network = { workspace = true, features = ["test-utils"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-tracing.workspace = true

# enable `test-utils` feature on this crate
hanzo-evm-ress-protocol = { path = ".", features = ["test-utils"] }

tokio.workspace = true
strum.workspace = true
strum_macros.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
proptest-arbitrary-interop.workspace = true

[features]
test-utils = [
    "hanzo-evm-network/test-utils",
    "hanzo-evm-ress-protocol/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
    "hanzo-evm-provider/test-utils",
]
arbitrary = [
    "dep:arbitrary",
    "hanzo-evm-eth-wire/arbitrary",
    "alloy-primitives/arbitrary",
    "hanzo-evm-ress-protocol/arbitrary",
    "hanzo-evm-ethereum-primitives/arbitrary",
    "alloy-consensus/arbitrary",
]
