[package]
name = "my-exex"
version = "0.1.0"
edition = "2024"

[dependencies]
reth = { git = "https://github.com/hanzoai/evm.git" } # Reth
hanzo-evm-exex = { git = "https://github.com/hanzoai/evm.git" } # Execution Extensions
hanzo-evm-node-ethereum = { git = "https://github.com/hanzoai/evm.git" } # Ethereum Node implementation
hanzo-evm-tracing = { git = "https://github.com/hanzoai/evm.git" } # Logging

eyre = "0.6" # Easy error handling
futures-util = "0.3" # Stream utilities for consuming notifications
