[package]
name = "hanzo-evm-stages-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-static-file.workspace = true
hanzo-evm-network-p2p.workspace = true
hanzo-evm-tokio-util.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-prune.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-stages-types.workspace = true
hanzo-evm-static-file-types.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
futures-util.workspace = true

# misc
aquamarine.workspace = true
thiserror.workspace = true
tracing.workspace = true
auto_impl.workspace = true

[dev-dependencies]
assert_matches.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-db = { workspace = true, features = ["test-utils"] }
hanzo-evm-db-api.workspace = true
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["sync", "rt-multi-thread"] }
tokio-stream.workspace = true
hanzo-evm-testing-utils.workspace = true

[features]
test-utils = [
    "hanzo-evm-chainspec/test-utils",
    "hanzo-evm-consensus/test-utils",
    "hanzo-evm-db-api/test-utils",
    "hanzo-evm-db/test-utils",
    "hanzo-evm-network-p2p/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-provider/test-utils",
    "hanzo-evm-stages-types/test-utils",
]
