[package]
name = "hanzo-evm-trie-sparse-parallel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Parallel Sparse MPT implementation"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-execution-errors.workspace = true
hanzo-evm-trie-common.workspace = true
hanzo-evm-trie-sparse.workspace = true
tracing = { workspace = true, features = ["attributes"] }
alloy-trie.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# metrics
hanzo-evm-metrics = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }

# misc
rayon = { workspace = true, optional = true }
smallvec.workspace = true

[dev-dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-trie-common = { workspace = true, features = ["test-utils", "arbitrary"] }
hanzo-evm-trie-db.workspace = true
hanzo-evm-trie-sparse = { workspace = true, features = ["test-utils"] }
hanzo-evm-trie.workspace = true
hanzo-evm-tracing.workspace = true

# misc
arbitrary.workspace = true
assert_matches.workspace = true
itertools.workspace = true
pretty_assertions.workspace = true
proptest-arbitrary-interop.workspace = true
proptest.workspace = true
rand.workspace = true
rand_08.workspace = true

[features]
default = ["std", "metrics"]
std = [
    "dep:rayon",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "alloy-trie/std",
    "hanzo-evm-execution-errors/std",
    "hanzo-evm-primitives-traits/std",
    "hanzo-evm-trie-common/std",
    "hanzo-evm-trie-sparse/std",
    "tracing/std",
]
metrics = [
    "dep:hanzo-evm-metrics",
    "dep:metrics",
    "std",
]
