[package]
name = "tracking-state"
version = "0.1.0"
edition = "2024"

[dependencies]
reth = { git = "https://github.com/hanzoai/evm.git" }
hanzo-evm-exex = { git = "https://github.com/hanzoai/evm.git", features = ["serde"] }
hanzo-evm-node-ethereum = { git = "https://github.com/hanzoai/evm.git" }
hanzo-evm-tracing = { git = "https://github.com/hanzoai/evm.git" }

eyre = "0.6" # Easy error handling
futures-util = "0.3" # Stream utilities for consuming notifications
alloy-primitives = "0.8.20"
