[package]
name = "hanzo-evm-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM RPC implementation"

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-primitives-traits.workspace = true
reth-rpc-api.workspace = true
reth-rpc-eth-api.workspace = true
reth-engine-primitives.workspace = true
reth-errors.workspace = true
reth-metrics.workspace = true
reth-storage-api.workspace = true
reth-execution-types = { workspace = true, features = ["serde"] }
reth-chain-state.workspace = true
reth-transaction-pool.workspace = true
reth-network-api.workspace = true
reth-rpc-engine-api.workspace = true
reth-revm = { workspace = true, features = ["witness"] }
reth-tasks = { workspace = true, features = ["rayon"] }
reth-rpc-convert.workspace = true
revm-inspectors.workspace = true
hanzo-evm-network-peers = { workspace = true, features = ["secp256k1"] }
hanzo-evm-execution.workspace = true
hanzo-evm-eth-execution.workspace = true
hanzo-evm-rpc-eth-types.workspace = true
hanzo-evm-rpc-server-types.workspace = true
hanzo-evm-network-types.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-consensus-common.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-trie-common.workspace = true

# ethereum
alloy-eip7928.workspace = true
alloy-evm = { workspace = true, features = ["overrides"] }
alloy-consensus.workspace = true
alloy-signer.workspace = true
alloy-signer-local = { workspace = true, features = ["mnemonic"] }
alloy-eips = { workspace = true, features = ["kzg"] }
alloy-dyn-abi.workspace = true
alloy-genesis.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rpc-client.workspace = true
alloy-rpc-types-beacon = { workspace = true, features = ["ssz"] }
alloy-rpc-types.workspace = true
alloy-rpc-types-eth = { workspace = true, features = ["serde"] }
alloy-rpc-types-debug.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-rpc-types-txpool.workspace = true
alloy-rpc-types-admin.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["kzg"] }
alloy-serde.workspace = true
revm = { workspace = true, features = ["optional_block_gas_limit", "optional_eip3607", "optional_no_base_fee", "memory_limit"] }
revm-primitives = { workspace = true, features = ["serde"] }

# rpc
jsonrpsee.workspace = true
serde_json.workspace = true
jsonrpsee-types.workspace = true

# async
async-trait.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
pin-project.workspace = true
parking_lot.workspace = true

# misc
dyn-clone.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
futures.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
derive_more.workspace = true
itertools.workspace = true

[dev-dependencies]
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-testing-utils.workspace = true
hanzo-evm-transaction-pool = { workspace = true, features = ["test-utils"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-db-api.workspace = true

rand.workspace = true

jsonrpsee = { workspace = true, features = ["client"] }

[features]
js-tracer = [
    "revm-inspectors/js-tracer",
    "hanzo-evm-rpc-eth-types/js-tracer",
    "hanzo-evm-rpc-eth-api/js-tracer",
]
