[package]
name = "hanzo-evm-stages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Staged syncing primitives used in Hanzo EVM."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-chainspec = { workspace = true, optional = true }
hanzo-evm-codecs.workspace = true
hanzo-evm-config.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-db.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-etl.workspace = true
hanzo-evm-execution = { workspace = true, features = ["metrics"] }
hanzo-evm-era-downloader.workspace = true
hanzo-evm-era-utils.workspace = true
hanzo-evm-era.workspace = true
hanzo-evm-exex.workspace = true
hanzo-evm-fs-util.workspace = true
hanzo-evm-network-p2p.workspace = true
hanzo-evm-primitives-traits = { workspace = true, features = ["serde-bincode-compat"] }
hanzo-evm-provider.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-ethereum-primitives = { workspace = true, optional = true }
hanzo-evm-prune.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-storage-errors.workspace = true
hanzo-evm-revm.workspace = true
hanzo-evm-stages-api.workspace = true
hanzo-evm-static-file-types.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-trie = { workspace = true, features = ["metrics"] }
hanzo-evm-trie-db = { workspace = true, features = ["metrics"] }

hanzo-evm-testing-utils = { workspace = true, optional = true }

alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
futures-util.workspace = true

# observability
tracing.workspace = true

# misc
thiserror.workspace = true
itertools.workspace = true
rayon.workspace = true
num-traits.workspace = true
tempfile = { workspace = true, optional = true }
bincode.workspace = true
reqwest.workspace = true
eyre.workspace = true

[dev-dependencies]
# evm
hanzo-evm-chainspec.workspace = true
hanzo-evm-db = { workspace = true, features = ["test-utils", "mdbx"] }
hanzo-evm-ethereum-primitives = { workspace = true, features = ["test-utils"] }
hanzo-evm-ethereum-consensus.workspace = true
hanzo-evm-eth-execution.workspace = true
hanzo-evm-consensus = { workspace = true, features = ["test-utils"] }
hanzo-evm-network-p2p = { workspace = true, features = ["test-utils"] }
hanzo-evm-downloaders = { workspace = true, features = ["file-client"] }
hanzo-evm-static-file.workspace = true
hanzo-evm-stages-api = { workspace = true, features = ["test-utils"] }
hanzo-evm-storage-api.workspace = true
hanzo-evm-testing-utils.workspace = true
hanzo-evm-trie = { workspace = true, features = ["test-utils"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-network-peers.workspace = true

alloy-genesis.workspace = true
alloy-primitives = { workspace = true, features = ["getrandom", "rand"] }
alloy-rlp.workspace = true
hanzo-evm-db-common.workspace = true
hanzo-evm-tracing.workspace = true

tokio = { workspace = true, features = ["rt", "sync", "macros"] }
assert_matches.workspace = true
rand.workspace = true
paste.workspace = true
tempfile.workspace = true

# Stage benchmarks
criterion = { workspace = true, features = ["async_tokio"] }

[features]
test-utils = [
    "dep:hanzo-evm-chainspec",
    "hanzo-evm-network-p2p/test-utils",
    "hanzo-evm-db/test-utils",
    "hanzo-evm-provider/test-utils",
    "hanzo-evm-stages-api/test-utils",
    "dep:hanzo-evm-testing-utils",
    "dep:tempfile",
    "hanzo-evm-chainspec?/test-utils",
    "hanzo-evm-consensus/test-utils",
    "hanzo-evm-execution/test-utils",
    "hanzo-evm-downloaders/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-revm/test-utils",
    "hanzo-evm-codecs/test-utils",
    "hanzo-evm-db-api/test-utils",
    "hanzo-evm-trie-db/test-utils",
    "hanzo-evm-trie/test-utils",
    "hanzo-evm-prune-types/test-utils",
    "dep:hanzo-evm-ethereum-primitives",
    "hanzo-evm-ethereum-primitives?/test-utils",
    "hanzo-evm-eth-execution/test-utils",
]
rocksdb = ["hanzo-evm-provider/rocksdb", "hanzo-evm-db-common/rocksdb"]
edge = ["rocksdb"]

[[bench]]
name = "criterion"
harness = false
required-features = ["test-utils"]
