[package]
name = "hanzo-evm-payload-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-chain-state.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-trie-common.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["serde"] }
op-alloy-rpc-types-engine = { workspace = true, optional = true, features = ["serde"] }

# misc
auto_impl.workspace = true
either.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["sync"] }

[dev-dependencies]
assert_matches.workspace = true

[features]
default = ["std"]
std = [
    "hanzo-evm-chainspec/std",
    "hanzo-evm-execution-types/std",
    "hanzo-evm-trie-common/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rpc-types-engine/std",
    "op-alloy-rpc-types-engine?/std",
    "serde/std",
    "thiserror/std",
    "hanzo-evm-primitives-traits/std",
    "either/std",
    "alloy-consensus/std",
]
op = [
    "dep:op-alloy-rpc-types-engine",
    "hanzo-evm-primitives-traits/op",
]
