[package]
name = "hanzo-evm-storage-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM storage provider traits and types"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-db-models.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-db-api = { workspace = true, optional = true }
hanzo-evm-execution-types.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-stages-types.workspace = true
hanzo-evm-storage-errors.workspace = true
hanzo-evm-trie-common.workspace = true
revm-database.workspace = true
hanzo-evm-ethereum-primitives.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-engine.workspace = true

auto_impl.workspace = true
serde_json = { workspace = true, optional = true }

[features]
default = ["std"]
rocksdb = ["hanzo-evm-db-api/rocksdb"]
edge = ["rocksdb"]
std = [
    "hanzo-evm-chainspec/std",
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rpc-types-engine/std",
    "hanzo-evm-primitives-traits/std",
    "hanzo-evm-stages-types/std",
    "revm-database/std",
    "hanzo-evm-ethereum-primitives/std",
    "hanzo-evm-execution-types/std",
    "hanzo-evm-prune-types/std",
    "hanzo-evm-storage-errors/std",
    "hanzo-evm-db-models/std",
    "hanzo-evm-trie-common/std",
    "serde_json?/std",
]

db-api = [
    "dep:hanzo-evm-db-api",
    "dep:serde_json",
]

serde = [
    "hanzo-evm-ethereum-primitives/serde",
    "hanzo-evm-db-models/serde",
    "hanzo-evm-execution-types/serde",
    "hanzo-evm-primitives-traits/serde",
    "hanzo-evm-prune-types/serde",
    "hanzo-evm-stages-types/serde",
    "hanzo-evm-trie-common/serde",
    "revm-database/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "alloy-consensus/serde",
    "alloy-rpc-types-engine/serde",
]

serde-bincode-compat = [
    "hanzo-evm-execution-types/serde-bincode-compat",
    "hanzo-evm-primitives-traits/serde-bincode-compat",
    "hanzo-evm-trie-common/serde-bincode-compat",
    "hanzo-evm-ethereum-primitives/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
    "alloy-consensus/serde-bincode-compat",
]
