[package]
name = "hanzo-evm-node-events"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-storage-api = { workspace = true, features = ["std"] }
hanzo-evm-network-api.workspace = true
hanzo-evm-stages.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-static-file-types.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-engine-primitives.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true

# async
tokio.workspace = true

# async
futures.workspace = true

tracing.workspace = true

# misc
pin-project.workspace = true
humantime.workspace = true
derive_more.workspace = true
