[package]
name = "hanzo-evm-exex-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
## evm
hanzo-evm-chainspec.workspace = true
hanzo-evm-config.workspace = true
hanzo-evm-consensus = { workspace = true, features = ["test-utils"] }
hanzo-evm-db = { workspace = true, features = ["test-utils"] }
hanzo-evm-db-common.workspace = true
hanzo-evm-eth-execution = { workspace = true, features = ["test-utils"] }
hanzo-evm-execution-types.workspace = true
hanzo-evm-exex.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-network.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-node-core.workspace = true
hanzo-evm-node-builder = { workspace = true, features = ["test-utils"] }
hanzo-evm-node-ethereum.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-tasks.workspace = true
hanzo-evm-transaction-pool = { workspace = true, features = ["test-utils"] }

## alloy
alloy-eips.workspace = true

## async
futures-util.workspace = true
tokio.workspace = true

## misc
eyre.workspace = true
tempfile.workspace = true
thiserror.workspace = true
