[package]
name = "hanzo-evm-storage-rpc-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "RPC-based blockchain provider for Hanzo EVM that fetches data via RPC calls"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-storage-api.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-primitives.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-node-types.workspace = true
hanzo-evm-trie.workspace = true
hanzo-evm-stages-types.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-rpc-convert.workspace = true

# alloy
alloy-provider = { workspace = true, features = ["debug-api"] }
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-eips.workspace = true

# async
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }

# other
tracing.workspace = true
dashmap = { workspace = true, features = ["inline"] }

# revm
revm.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
