[package]
name = "example-custom-node-components"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
hanzo-evm-ethereum = { workspace = true, features = ["node", "pool", "node-api", "cli"] }
hanzo-evm-tracing.workspace = true

eyre.workspace = true
