[package]
name = "hanzo-evm-node-ethstats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
hanzo-evm-network-api.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-chain-state.workspace = true

alloy-primitives.workspace = true
alloy-consensus.workspace = true

tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
tokio-stream.workspace = true

serde.workspace = true
serde_json.workspace = true

tracing.workspace = true
url.workspace = true
chrono.workspace = true
thiserror = { workspace = true, features = ["std"] }
