[package]
name = "example-db-access"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
hanzo-evm-ethereum = { workspace = true, features = ["node"] }
alloy-primitives.workspace = true

eyre.workspace = true
