[package]
name = "hanzo-evm-rpc-convert"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Compatibility layer for hanzo-evm-primitives and ethereum RPC types"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-ethereum-primitives.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-rpc-types-eth = { workspace = true, features = ["serde"] }
alloy-signer.workspace = true
alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-json-rpc.workspace = true
alloy-evm = { workspace = true, features = ["rpc"] }

# optimism
op-alloy-consensus = { workspace = true, optional = true }
op-alloy-rpc-types = { workspace = true, optional = true }
op-alloy-network = { workspace = true, optional = true }

# io
jsonrpsee-types.workspace = true

# error
thiserror.workspace = true

auto_impl.workspace = true
dyn-clone.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
default = []
op = [
    "dep:op-alloy-consensus",
    "dep:op-alloy-rpc-types",
    "dep:op-alloy-network",
    "hanzo-evm-execution/op",
    "hanzo-evm-primitives-traits/op",
    "alloy-evm/op",
]
