[package]
name = "hanzo-evm-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Merkle trie implementation"

[lints]
workspace = true

[dependencies]
# reth
reth-execution-errors.workspace = true
reth-primitives-traits = { workspace = true, features = ["std"] }
reth-stages-types.workspace = true
reth-storage-errors.workspace = true
reth-trie-sparse.workspace = true
reth-trie-common = { workspace = true, features = ["rayon"] }

revm-database.workspace = true

# alloy
alloy-eips.workspace = true
alloy-rlp.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-trie.workspace = true

# tracing
tracing = { workspace = true, features = ["attributes"] }

# misc
auto_impl.workspace = true
itertools.workspace = true

# `metrics` feature
hanzo-evm-metrics = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }

# `test-utils` feature
triehash = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }

[dev-dependencies]
# evm
hanzo-evm-ethereum-primitives = { workspace = true, features = ["arbitrary", "std"] }
hanzo-evm-primitives-traits = { workspace = true, features = ["test-utils"] }
hanzo-evm-tracing.workspace = true
hanzo-evm-trie-common = { workspace = true, features = ["test-utils", "arbitrary"] }

# revm
revm-state.workspace = true

# trie
triehash.workspace = true

# misc
assert_matches.workspace = true
criterion.workspace = true
parking_lot.workspace = true
pretty_assertions.workspace = true
proptest-arbitrary-interop.workspace = true
proptest.workspace = true
rand.workspace = true

[features]
metrics = ["hanzo-evm-metrics", "dep:metrics"]
serde = [
    "alloy-primitives/serde",
    "alloy-consensus/serde",
    "alloy-trie/serde",
    "alloy-eips/serde",
    "hanzo-evm-trie-common/serde",
    "hanzo-evm-primitives-traits/serde",
    "alloy-primitives/serde",
    "alloy-consensus/serde",
    "alloy-trie/serde",
    "alloy-eips/serde",
    "hanzo-evm-trie-common/serde",
    "revm-database/serde",
    "hanzo-evm-stages-types/serde",
    "revm-state/serde",
    "parking_lot/serde",
    "hanzo-evm-ethereum-primitives/serde",
    "rand/serde",
]
test-utils = [
    "triehash",
    "parking_lot",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-trie-common/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
    "hanzo-evm-trie-sparse/test-utils",
    "hanzo-evm-stages-types/test-utils",
]
serde-bincode-compat = [
    "alloy-consensus/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
    "hanzo-evm-ethereum-primitives/serde-bincode-compat",
    "hanzo-evm-primitives-traits/serde-bincode-compat",
    "hanzo-evm-trie-common/serde-bincode-compat",
]

[[bench]]
name = "hash_post_state"
harness = false

[[bench]]
name = "trie_root"
required-features = ["test-utils"]
harness = false

[[bench]]
name = "proof_v2"
required-features = ["test-utils"]
harness = false
