[package]
name = "hanzo-evm-basic-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A basic payload builder for Hanzo EVM that uses the txpool API to build payloads."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-payload-builder-primitives.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-revm.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-chain-state.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true

# async
tokio = { workspace = true, features = ["sync", "time"] }
futures-core.workspace = true
futures-util.workspace = true

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true

# misc
tracing.workspace = true
