scrape_configs:
  - job_name: evm
    metrics_path: "/"
    scrape_interval: 5s
    static_configs:
      - targets: ['evm:9001', 'localhost:9001', 'host.docker.internal:9001']
  - job_name: ethereum-metrics-exporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ['metrics-exporter:9091']