[package]
name = "hanzo-evm-execution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-execution-errors.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-metrics = { workspace = true, optional = true }
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-storage-errors.workspace = true
hanzo-evm-trie-common.workspace = true

revm.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-consensus.workspace = true

auto_impl.workspace = true
derive_more.workspace = true
futures-util.workspace = true
metrics = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }

[dev-dependencies]
hanzo-evm-ethereum-primitives.workspace = true

[features]
default = ["std"]
std = [
    "dep:rayon",
    "hanzo-evm-primitives-traits/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-consensus/std",
    "revm/std",
    "alloy-evm/std",
    "hanzo-evm-execution-errors/std",
    "hanzo-evm-execution-types/std",
    "hanzo-evm-storage-errors/std",
    "futures-util/std",
    "derive_more/std",
    "hanzo-evm-storage-api/std",
    "hanzo-evm-trie-common/std",
    "hanzo-evm-ethereum-primitives/std",
]
metrics = ["std", "dep:metrics", "dep:hanzo-evm-metrics"]
test-utils = [
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-trie-common/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
]
op = ["alloy-evm/op", "hanzo-evm-primitives-traits/op"]
