[package]
name = "hanzo-evm-node-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-ethereum-payload-builder.workspace = true
hanzo-evm-ethereum-consensus.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
## ensure secp256k1 recovery with rayon support is activated
hanzo-evm-primitives-traits = { workspace = true, features = ["secp256k1", "rayon"] }
hanzo-evm-node-builder.workspace = true
hanzo-evm-tracing.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-network.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-eth-execution = { workspace = true, features = ["std"] }
hanzo-evm-rpc.workspace = true
hanzo-evm-rpc-api.workspace = true
hanzo-evm-rpc-eth-api.workspace = true
hanzo-evm-rpc-builder.workspace = true
hanzo-evm-rpc-server-types.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-revm = { workspace = true, features = ["std"] }
hanzo-evm-rpc-eth-types.workspace = true
hanzo-evm-engine-local.workspace = true
hanzo-evm-engine-primitives = { workspace = true, features = ["std"] }
hanzo-evm-payload-primitives.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-engine.workspace = true

# async
tokio.workspace = true

# revm with required ethereum features
# Note: this must be kept to ensure all features are properly enabled/forwarded
revm = { workspace = true, features = ["secp256k1", "blst", "c-kzg", "memory_limit"] }

# misc
eyre.workspace = true

[dev-dependencies]
hanzo-evm-db.workspace = true
hanzo-evm-exex.workspace = true
hanzo-evm-node-core.workspace = true
hanzo-evm-e2e-test-utils.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-testing-utils.workspace = true
hanzo-evm-stages-types.workspace = true
tempfile.workspace = true
jsonrpsee-core.workspace = true

alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-genesis.workspace = true
alloy-signer.workspace = true
alloy-sol-types.workspace = true
alloy-contract.workspace = true
alloy-rpc-types-beacon = { workspace = true, features = ["ssz"] }
alloy-consensus.workspace = true

futures.workspace = true
tokio.workspace = true
serde_json.workspace = true
rand.workspace = true
serde.workspace = true
alloy-rpc-types-trace.workspace = true
similar-asserts.workspace = true

[features]
default = []
asm-keccak = [
    "alloy-primitives/asm-keccak",
    "hanzo-evm-node-core/asm-keccak",
    "revm/asm-keccak",
]
keccak-cache-global = [
    "alloy-primitives/keccak-cache-global",
    "hanzo-evm-node-core/keccak-cache-global",
]
js-tracer = [
    "hanzo-evm-node-builder/js-tracer",
    "hanzo-evm-rpc/js-tracer",
    "hanzo-evm-rpc-eth-api/js-tracer",
    "hanzo-evm-rpc-eth-types/js-tracer",
]
test-utils = [
    "reth-node-builder/test-utils",
    "reth-chainspec/test-utils",
    "reth-network/test-utils",
    "reth-ethereum-primitives/test-utils",
    "reth-revm/test-utils",
    "reth-db/test-utils",
    "reth-provider/test-utils",
    "reth-transaction-pool/test-utils",
    "reth-evm/test-utils",
    "reth-primitives-traits/test-utils",
    "reth-evm-ethereum/test-utils",
    "reth-stages-types/test-utils",
    "reth-tasks/test-utils",
]
