[package]
name = "hanzo-evm-storage-errors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-static-file-types.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# misc
derive_more.workspace = true
thiserror.workspace = true

revm-database-interface.workspace = true
revm-state.workspace = true

[features]
default = ["std"]
std = [
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "derive_more/std",
    "hanzo-evm-primitives-traits/std",
    "thiserror/std",
    "revm-database-interface/std",
    "hanzo-evm-prune-types/std",
    "hanzo-evm-static-file-types/std",
    "revm-state/std",
]
