[package]
name = "hanzo-evm-db-models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Database models used in storage module."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-codecs = { workspace = true, optional = true }
hanzo-evm-primitives-traits.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-eips.workspace = true

# codecs
modular-bitfield = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

# misc
bytes = { workspace = true, optional = true }

# arbitrary utils
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
# evm
hanzo-evm-primitives-traits = { workspace = true, features = ["arbitrary", "hanzo-evm-codec"] }
hanzo-evm-codecs.workspace = true

bytes.workspace = true
arbitrary = { workspace = true, features = ["derive"] }

proptest.workspace = true
proptest-arbitrary-interop.workspace = true

[features]
default = ["std"]
std = [
    "alloy-eips/std",
    "alloy-primitives/std",
    "hanzo-evm-primitives-traits/std",
    "bytes?/std",
    "serde?/std",
]
serde = [
    "dep:serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "bytes?/serde",
    "hanzo-evm-codecs?/serde",
    "hanzo-evm-primitives-traits/serde",
]
test-utils = [
    "hanzo-evm-primitives-traits/test-utils",
    "arbitrary",
    "hanzo-evm-codecs?/test-utils",
]
arbitrary = [
    "std",
    "hanzo-evm-primitives-traits/arbitrary",
    "dep:arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-eips/arbitrary",
    "hanzo-evm-codecs?/arbitrary",
]
hanzo-evm-codec = [
    "dep:hanzo-evm-codecs",
    "dep:modular-bitfield",
    "dep:bytes",
    "hanzo-evm-primitives-traits/hanzo-evm-codec",
]
