[package]
name = "hanzo-evm-db-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Database abstraction used in Hanzo EVM."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-codecs.workspace = true
hanzo-evm-db-models = { workspace = true, features = ["serde", "hanzo-evm-codec"] }
hanzo-evm-ethereum-primitives = { workspace = true, features = ["serde", "hanzo-evm-codec"] }
hanzo-evm-primitives-traits = { workspace = true, features = ["serde", "hanzo-evm-codec"] }
hanzo-evm-stages-types = { workspace = true, features = ["serde", "hanzo-evm-codec"] }
hanzo-evm-prune-types = { workspace = true, features = ["serde", "hanzo-evm-codec"] }
hanzo-evm-storage-errors.workspace = true
hanzo-evm-trie-common.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-genesis.workspace = true
alloy-consensus.workspace = true

# op
op-alloy-consensus = { workspace = true, optional = true }

# codecs
modular-bitfield.workspace = true
roaring.workspace = true
parity-scale-codec = { workspace = true, features = ["bytes"] }
serde = { workspace = true, default-features = false }

# metrics
metrics.workspace = true

# misc
arrayvec.workspace = true
derive_more.workspace = true
bytes.workspace = true

# arbitrary utils
arbitrary = { workspace = true, features = ["derive"], optional = true }
proptest = { workspace = true, optional = true }

[dev-dependencies]
# evm libs with arbitrary
hanzo-evm-codecs = { workspace = true, features = ["test-utils"] }
hanzo-evm-db-models = { workspace = true, features = ["arbitrary"] }

alloy-primitives = { workspace = true, features = ["rand"] }
rand.workspace = true

test-fuzz.workspace = true

arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
proptest-arbitrary-interop.workspace = true

[features]
test-utils = [
    "arbitrary",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-codecs/test-utils",
    "hanzo-evm-db-models/test-utils",
    "hanzo-evm-trie-common/test-utils",
    "hanzo-evm-prune-types/test-utils",
    "hanzo-evm-stages-types/test-utils",
    "hanzo-evm-ethereum-primitives/test-utils",
]
arbitrary = [
    "hanzo-evm-db-models/arbitrary",
    "dep:arbitrary",
    "dep:proptest",
    "hanzo-evm-primitives-traits/arbitrary",
    "hanzo-evm-trie-common/arbitrary",
    "alloy-primitives/arbitrary",
    "parity-scale-codec/arbitrary",
    "hanzo-evm-codecs/arbitrary",
    "hanzo-evm-prune-types/arbitrary",
    "hanzo-evm-stages-types/arbitrary",
    "alloy-consensus/arbitrary",
    "op-alloy-consensus?/arbitrary",
    "hanzo-evm-ethereum-primitives/arbitrary",
]
op = [
    "dep:op-alloy-consensus",
    "hanzo-evm-codecs/op",
    "hanzo-evm-primitives-traits/op",
]
bench = []
rocksdb = []
edge = ["rocksdb"]
