[package]
name = "hanzo-evm-db-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# evm
hanzo-evm-chainspec.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-config.workspace = true
hanzo-evm-trie.workspace = true
hanzo-evm-trie-db.workspace = true
hanzo-evm-etl.workspace = true
hanzo-evm-codecs.workspace = true
hanzo-evm-stages-types.workspace = true
hanzo-evm-fs-util.workspace = true
hanzo-evm-node-types.workspace = true
hanzo-evm-static-file-types.workspace = true
hanzo-evm-execution-errors.workspace = true

# eth
alloy-consensus.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true

# misc
eyre.workspace = true
thiserror.workspace = true
boyer-moore-magiclen.workspace = true

# io
serde.workspace = true
serde_json.workspace = true

# tracing
tracing.workspace = true

[dev-dependencies]
hanzo-evm-db = { workspace = true, features = ["mdbx"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }

[features]
rocksdb = ["hanzo-evm-db-api/rocksdb", "hanzo-evm-provider/rocksdb"]
edge = ["rocksdb"]

[lints]
workspace = true
