[package]
name = "hanzo-evm-stages-types"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Commonly used types for stages usage in Hanzo EVM."

[lints]
workspace = true

[dependencies]
hanzo-evm-codecs = { workspace = true, optional = true }
hanzo-evm-trie-common.workspace = true
alloy-primitives.workspace = true

serde = { workspace = true, optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }

bytes = { workspace = true, optional = true }
modular-bitfield = { workspace = true, optional = true }

[dev-dependencies]
hanzo-evm-codecs.workspace = true
hanzo-evm-trie-common = { workspace = true, features = ["hanzo-evm-codec"] }
alloy-primitives = { workspace = true, features = ["arbitrary", "rand"] }
arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
proptest-arbitrary-interop.workspace = true
rand.workspace = true
bytes.workspace = true
modular-bitfield.workspace = true

[features]
default = ["std"]
std = [
    "alloy-primitives/std",
    "bytes?/std",
    "hanzo-evm-trie-common/std",
    "serde?/std",
]
hanzo-evm-codec = [
    "dep:hanzo-evm-codecs",
    "dep:bytes",
    "dep:modular-bitfield",
    "hanzo-evm-trie-common/hanzo-evm-codec",
]
test-utils = [
    "arbitrary",
    "hanzo-evm-codecs?/test-utils",
    "hanzo-evm-trie-common/test-utils",
]
arbitrary = [
    "std",
    "dep:arbitrary",
    "alloy-primitives/arbitrary",
    "hanzo-evm-codecs?/arbitrary",
    "hanzo-evm-trie-common/arbitrary",
]
serde = [
    "dep:serde",
    "alloy-primitives/serde",
    "bytes?/serde",
    "rand/serde",
    "hanzo-evm-codecs?/serde",
    "hanzo-evm-trie-common/serde",
]
