[package]
name = "hanzo-evm-ress-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
hanzo-evm-ress-protocol.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-revm = { workspace = true, features = ["witness"] }
hanzo-evm-chain-state.workspace = true
hanzo-evm-trie.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-tokio-util.workspace = true
hanzo-evm-node-api.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true

# misc
futures.workspace = true
tokio.workspace = true
parking_lot.workspace = true
schnellru.workspace = true
eyre.workspace = true
tracing.workspace = true
