[package]
name = "hanzo-evm-rpc-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM RPC interfaces"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-rpc-eth-api.workspace = true
hanzo-evm-engine-primitives.workspace = true
hanzo-evm-network-peers.workspace = true
hanzo-evm-trie-common.workspace = true
hanzo-evm-chain-state.workspace = true

# ethereum
alloy-eip7928 = { workspace = true, features = ["serde"] }
alloy-eips.workspace = true
alloy-json-rpc.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-debug.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-rpc-types-anvil.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-rpc-types-txpool.workspace = true
alloy-rpc-types-admin.workspace = true
alloy-serde.workspace = true
alloy-rpc-types-beacon.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-genesis.workspace = true

# misc
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[features]
client = [
    "jsonrpsee/client",
    "jsonrpsee/async-client",
    "hanzo-evm-rpc-eth-api/client",
]

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
jsonrpsee = { workspace = true, features = ["client", "async-client", "http-client"] }
