[package]
name = "hanzo-evm-rpc-api-testing-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM RPC testing helpers"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-rpc-api = { workspace = true, features = ["client"] }

# ethereum
alloy-primitives.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-eips.workspace = true

# async
futures.workspace = true

# misc
jsonrpsee = { workspace = true, features = ["client", "async-client"] }
serde_json.workspace = true

# assertions
similar-asserts.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "rt"] }
hanzo-evm-rpc-eth-api.workspace = true
jsonrpsee-http-client.workspace = true
