[package]
name = "hanzo-evm-node-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
## evm
hanzo-evm-chain-state.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-config.workspace = true
hanzo-evm-consensus-debug-client.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-db = { workspace = true, features = ["mdbx"] }
hanzo-evm-db-api.workspace = true
hanzo-evm-db-common.workspace = true
hanzo-evm-downloaders.workspace = true
hanzo-evm-engine-local.workspace = true
hanzo-evm-engine-primitives.workspace = true
hanzo-evm-engine-service.workspace = true
hanzo-evm-engine-tree.workspace = true
hanzo-evm-engine-util.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-exex.workspace = true
hanzo-evm-fs-util.workspace = true
hanzo-evm-invalid-block-hooks.workspace = true
hanzo-evm-network-api.workspace = true
hanzo-evm-network-p2p.workspace = true
hanzo-evm-network.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-node-core.workspace = true
hanzo-evm-node-events.workspace = true
hanzo-evm-node-metrics.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-prune.workspace = true
hanzo-evm-rpc.workspace = true
hanzo-evm-rpc-api.workspace = true
hanzo-evm-rpc-builder.workspace = true
hanzo-evm-rpc-engine-api.workspace = true
hanzo-evm-rpc-eth-types.workspace = true
hanzo-evm-rpc-layer.workspace = true
hanzo-evm-stages.workspace = true
hanzo-evm-static-file.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-tokio-util.workspace = true
hanzo-evm-tracing.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-trie-db = { workspace = true, features = ["metrics"] }
hanzo-evm-basic-payload-builder.workspace = true
hanzo-evm-node-ethstats.workspace = true

## ethereum
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types = { workspace = true, features = ["engine"] }
alloy-eips = { workspace = true, features = ["kzg"] }
alloy-rpc-types-engine.workspace = true

## async
futures.workspace = true
tokio = { workspace = true, features = ["sync", "macros", "time", "rt-multi-thread"] }
tokio-stream.workspace = true

## crypto
secp256k1 = { workspace = true, features = ["global-context", "std", "recovery"] }

## misc
aquamarine.workspace = true
eyre.workspace = true
parking_lot.workspace = true
jsonrpsee.workspace = true
fdlimit.workspace = true
rayon.workspace = true
serde_json.workspace = true

# tracing
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-payload-builder = { workspace = true, features = ["test-utils"] }
hanzo-evm-node-ethereum.workspace = true
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-eth-execution = { workspace = true, features = ["test-utils"] }

[features]
default = []
js-tracer = [
    "hanzo-evm-rpc/js-tracer",
    "hanzo-evm-node-ethereum/js-tracer",
    "hanzo-evm-rpc-eth-types/js-tracer",
]
test-utils = [
    "hanzo-evm-db/test-utils",
    "hanzo-evm-chain-state/test-utils",
    "hanzo-evm-chainspec/test-utils",
    "hanzo-evm-consensus/test-utils",
    "hanzo-evm-engine-tree/test-utils",
    "hanzo-evm-execution/test-utils",
    "hanzo-evm-downloaders/test-utils",
    "hanzo-evm-network/test-utils",
    "hanzo-evm-network-p2p/test-utils",
    "hanzo-evm-payload-builder/test-utils",
    "hanzo-evm-stages/test-utils",
    "hanzo-evm-db-api/test-utils",
    "hanzo-evm-provider/test-utils",
    "hanzo-evm-transaction-pool/test-utils",
    "hanzo-evm-trie-db/test-utils",
    "hanzo-evm-eth-execution/test-utils",
    "hanzo-evm-node-ethereum/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
]
op = [
    "hanzo-evm-db/op",
    "hanzo-evm-db-api/op",
    "hanzo-evm-engine-local/op",
    "hanzo-evm-execution/op",
    "hanzo-evm-primitives-traits/op",
]
