[package]
name = "hanzo-evm-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution extensions for Reth"

[lints]
workspace = true

[dependencies]
## evm
hanzo-evm-chain-state.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-config.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-exex-types = { workspace = true, features = ["serde", "serde-bincode-compat"] }
hanzo-evm-fs-util.workspace = true
hanzo-evm-metrics.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-node-core.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-revm.workspace = true
hanzo-evm-stages-api.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-tracing.workspace = true
hanzo-evm-payload-builder.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-eips.workspace = true

## async
futures.workspace = true
tokio-util.workspace = true
tokio.workspace = true

## misc
eyre.workspace = true
itertools = { workspace = true, features = ["use_std"] }
metrics.workspace = true
parking_lot.workspace = true
rmp-serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
hanzo-evm-db-common.workspace = true
hanzo-evm-eth-execution.workspace = true
hanzo-evm-primitives-traits = { workspace = true, features = ["test-utils"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-testing-utils.workspace = true
hanzo-evm-trie-common = { workspace = true, features = ["serde-bincode-compat"] }

alloy-genesis.workspace = true

rand.workspace = true
secp256k1.workspace = true
tempfile.workspace = true

[features]
default = []
edge = ["hanzo-evm-provider/edge"]
serde = [
    "hanzo-evm-exex-types/serde",
    "hanzo-evm-revm/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "parking_lot/serde",
    "rand/serde",
    "secp256k1/serde",
    "hanzo-evm-primitives-traits/serde",
    "hanzo-evm-trie-common/serde",
    "hanzo-evm-prune-types/serde",
    "hanzo-evm-config/serde",
    "hanzo-evm-ethereum-primitives/serde",
    "hanzo-evm-chain-state/serde",
]
