[package]
name = "hanzo-evm-prune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Pruning implementation"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-exex-types.workspace = true
hanzo-evm-db-api.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-tokio-util.workspace = true
hanzo-evm-config.workspace = true
hanzo-evm-prune-types.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-stages-types.workspace = true
hanzo-evm-static-file-types.workspace = true

# ethereum
alloy-consensus.workspace = true
alloy-eips.workspace = true

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true
alloy-primitives.workspace = true

# misc
tracing.workspace = true
thiserror.workspace = true
itertools.workspace = true
rayon.workspace = true
tokio.workspace = true
rustc-hash.workspace = true

[features]
rocksdb = ["hanzo-evm-provider/rocksdb"]

[dev-dependencies]
# evm
hanzo-evm-db = { workspace = true, features = ["test-utils"] }
hanzo-evm-stages = { workspace = true, features = ["test-utils", "rocksdb"] }
hanzo-evm-primitives-traits = { workspace = true, features = ["arbitrary"] }
hanzo-evm-storage-api.workspace = true
hanzo-evm-testing-utils.workspace = true
hanzo-evm-tracing.workspace = true

assert_matches.workspace = true
