[package]
name = "example-network-txpool"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
hanzo-evm-ethereum = { workspace = true, features = ["test-utils", "network", "pool", "provider"] }
eyre.workspace = true
tokio.workspace = true
