[package]
name = "hanzo-evm-engine-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-consensus.workspace = true
hanzo-evm-engine-tree.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-network-p2p.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-provider.workspace = true
hanzo-evm-prune.workspace = true
hanzo-evm-stages-api.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-node-types.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-engine-primitives.workspace = true
hanzo-evm-trie-db.workspace = true

# async
futures.workspace = true
pin-project.workspace = true

# misc

[dev-dependencies]
hanzo-evm-engine-tree = { workspace = true, features = ["test-utils"] }
hanzo-evm-ethereum-consensus.workspace = true
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-eth-execution.workspace = true
hanzo-evm-exex-types.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-node-ethereum.workspace = true
hanzo-evm-trie-db.workspace = true

alloy-eips.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
