[package]
name = "hanzo-evm-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM payload builder"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-chain-state.workspace = true
hanzo-evm-payload-builder-primitives.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-ethereum-engine-primitives.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types = { workspace = true, features = ["engine"] }

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
futures-util.workspace = true

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true

# misc
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["sync", "rt"] }

[features]
test-utils = [
    "hanzo-evm-chain-state/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "tokio/rt",
]
