[package]
name = "hanzo-evm-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM storage provider."

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-execution-types.workspace = true
reth-ethereum-primitives = { workspace = true, features = ["reth-codec"] }
reth-primitives-traits = { workspace = true, features = ["reth-codec", "secp256k1", "dashmap"] }
reth-errors.workspace = true
reth-storage-errors.workspace = true
reth-storage-api = { workspace = true, features = ["std", "db-api"] }
reth-db = { workspace = true, features = ["mdbx"] }
reth-db-api.workspace = true
reth-prune-types.workspace = true
reth-stages-types.workspace = true
reth-tasks = { workspace = true, features = ["rayon"] }
reth-trie = { workspace = true, features = ["metrics"] }
reth-trie-db = { workspace = true, features = ["metrics"] }
reth-nippy-jar.workspace = true
reth-codecs.workspace = true
reth-chain-state.workspace = true
reth-node-types.workspace = true
reth-static-file-types = { workspace = true, features = ["std"] }
reth-fs-util.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-consensus.workspace = true
revm-database.workspace = true
revm-state = { workspace = true, optional = true }

# tracing
tracing.workspace = true

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true

# misc
itertools.workspace = true
notify = { workspace = true, default-features = false, features = ["macos_fsevent"] }
parking_lot.workspace = true
strum.workspace = true
eyre.workspace = true

# test-utils
hanzo-evm-ethereum-engine-primitives = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync"], optional = true }

# parallel utils
rayon.workspace = true

[target.'cfg(unix)'.dependencies]
# rocksdb: jemalloc is recommended production workload
rocksdb = { workspace = true, features = ["jemalloc"], optional = true }

[dev-dependencies]
hanzo-evm-db = { workspace = true, features = ["test-utils"] }
hanzo-evm-primitives-traits = { workspace = true, features = ["arbitrary", "test-utils"] }
hanzo-evm-chain-state = { workspace = true, features = ["test-utils"] }
hanzo-evm-trie = { workspace = true, features = ["test-utils"] }
hanzo-evm-testing-utils.workspace = true
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-tracing.workspace = true

revm-database-interface.workspace = true
revm-state.workspace = true

tempfile.workspace = true
assert_matches.workspace = true
rand.workspace = true

tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }

[features]
rocksdb = ["hanzo-evm-storage-api/rocksdb", "dep:rocksdb"]
edge = ["rocksdb"]
test-utils = [
    "hanzo-evm-db/test-utils",
    "hanzo-evm-nippy-jar/test-utils",
    "hanzo-evm-trie/test-utils",
    "hanzo-evm-chain-state/test-utils",
    "hanzo-evm-ethereum-engine-primitives",
    "hanzo-evm-ethereum-primitives/test-utils",
    "hanzo-evm-chainspec/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-codecs/test-utils",
    "hanzo-evm-db-api/test-utils",
    "hanzo-evm-trie-db/test-utils",
    "hanzo-evm-prune-types/test-utils",
    "hanzo-evm-stages-types/test-utils",
    "revm-state",
    "tokio",
    "reth-tasks/test-utils",
]
