[package]
name = "hanzo-evm-ethereum-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-execution-types.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-consensus-common.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-consensus.workspace = true

# alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true

tracing.workspace = true

[features]
default = ["std"]
std = [
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "hanzo-evm-chainspec/std",
    "hanzo-evm-consensus/std",
    "hanzo-evm-consensus-common/std",
    "hanzo-evm-ethereum-primitives/std",
    "hanzo-evm-execution-types/std",
    "hanzo-evm-primitives-traits/std",
    "tracing/std",
]

[dev-dependencies]
hanzo-evm-ethereum-primitives.workspace = true
alloy-primitives = { workspace = true, features = ["getrandom"] }
