[package]
name = "hanzo-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Hanzo EVM node implementation"
default-run = "hanzo-evm"

[package.metadata.deb]
maintainer = "hanzo evm team"
depends = "$auto"
section = "network"
priority = "optional"
maintainer-scripts = "../../pkg/evm/debian/"
assets = [
    "$auto",
    ["../../README.md", "usr/share/doc/evm/", "644"],
    ["../../LICENSE-APACHE", "usr/share/doc/evm/", "644"],
    ["../../LICENSE-MIT", "usr/share/doc/evm/", "644"],
]
systemd-units = { enable = false, start = false, unit-name = "hanzo-evm", unit-scripts = "../../pkg/evm/debian" }

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-ethereum-cli.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-primitives.workspace = true
hanzo-evm-db = { workspace = true, features = ["mdbx"] }
hanzo-evm-provider.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-revm.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-cli-runner.workspace = true
hanzo-evm-cli-util.workspace = true
hanzo-evm-consensus-common.workspace = true
hanzo-evm-rpc-builder.workspace = true
hanzo-evm-rpc.workspace = true
hanzo-evm-rpc-convert.workspace = true
hanzo-evm-rpc-api = { workspace = true, features = ["client"] }
hanzo-evm-rpc-eth-types.workspace = true
hanzo-evm-rpc-server-types.workspace = true
hanzo-evm-network = { workspace = true, features = ["serde"] }
hanzo-evm-network-api.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-node-api.workspace = true
hanzo-evm-node-core.workspace = true
hanzo-evm-ethereum-payload-builder.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-node-ethereum.workspace = true
hanzo-evm-node-builder.workspace = true
hanzo-evm-node-metrics.workspace = true
hanzo-evm-consensus.workspace = true
hanzo-evm-tokio-util.workspace = true
hanzo-evm-ress-protocol.workspace = true
hanzo-evm-ress-provider.workspace = true

# alloy
alloy-rpc-types = { workspace = true, features = ["engine"] }

# tracing
tracing.workspace = true

# async
tokio = { workspace = true, features = ["sync", "macros", "time", "rt-multi-thread"] }

# misc
aquamarine.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true

[dev-dependencies]
backon.workspace = true
tempfile.workspace = true

[features]
default = [
    "jemalloc",
    "otlp",
    "otlp-logs",
    "hanzo-evm-revm/portable",
    "js-tracer",
    "keccak-cache-global",
    "asm-keccak",
    "rocksdb",
]

otlp = [
    "hanzo-evm-ethereum-cli/otlp",
    "hanzo-evm-node-core/otlp",
]
otlp-logs = [
    "hanzo-evm-ethereum-cli/otlp-logs",
    "hanzo-evm-node-core/otlp-logs",
]
js-tracer = [
    "hanzo-evm-node-builder/js-tracer",
    "hanzo-evm-node-ethereum/js-tracer",
    "hanzo-evm-rpc/js-tracer",
    "hanzo-evm-rpc-eth-types/js-tracer",
]

dev = ["hanzo-evm-ethereum-cli/dev"]

asm-keccak = [
    "hanzo-evm-node-core/asm-keccak",
    "hanzo-evm-primitives/asm-keccak",
    "hanzo-evm-ethereum-cli/asm-keccak",
    "hanzo-evm-node-ethereum/asm-keccak",
]
keccak-cache-global = [
    "hanzo-evm-node-core/keccak-cache-global",
    "hanzo-evm-node-ethereum/keccak-cache-global",
]
jemalloc = [
    "hanzo-evm-cli-util/jemalloc",
    "hanzo-evm-node-core/jemalloc",
    "hanzo-evm-node-metrics/jemalloc",
    "hanzo-evm-ethereum-cli/jemalloc",
]
jemalloc-prof = [
    "hanzo-evm-cli-util/jemalloc",
    "hanzo-evm-cli-util/jemalloc-prof",
    "hanzo-evm-ethereum-cli/jemalloc-prof",
    "hanzo-evm-node-metrics/jemalloc-prof",
]
jemalloc-symbols = [
    "jemalloc-prof",
    "hanzo-evm-ethereum-cli/jemalloc-symbols",
]
jemalloc-unprefixed = [
    "hanzo-evm-cli-util/jemalloc-unprefixed",
    "hanzo-evm-node-core/jemalloc",
    "hanzo-evm-node-metrics/jemalloc",
    "hanzo-evm-ethereum-cli/jemalloc",
]
tracy-allocator = [
    "hanzo-evm-cli-util/tracy-allocator",
    "hanzo-evm-ethereum-cli/tracy-allocator",
    "tracy",
]
tracy = [
    "hanzo-evm-ethereum-cli/tracy",
    "hanzo-evm-node-core/tracy",
]

# Because jemalloc is default and preferred over snmalloc when both features are
# enabled, `--no-default-features` should be used when enabling snmalloc or
# snmalloc-native.
snmalloc = [
    "hanzo-evm-cli-util/snmalloc",
    "hanzo-evm-ethereum-cli/snmalloc",
]
snmalloc-native = [
    "hanzo-evm-cli-util/snmalloc-native",
    "hanzo-evm-ethereum-cli/snmalloc-native",
]

min-error-logs = [
    "tracing/release_max_level_error",
    "hanzo-evm-ethereum-cli/min-error-logs",
    "hanzo-evm-node-core/min-error-logs",
]
min-warn-logs = [
    "tracing/release_max_level_warn",
    "hanzo-evm-ethereum-cli/min-warn-logs",
    "hanzo-evm-node-core/min-warn-logs",
]
min-info-logs = [
    "tracing/release_max_level_info",
    "hanzo-evm-ethereum-cli/min-info-logs",
    "hanzo-evm-node-core/min-info-logs",
]
min-debug-logs = [
    "tracing/release_max_level_debug",
    "hanzo-evm-ethereum-cli/min-debug-logs",
    "hanzo-evm-node-core/min-debug-logs",
]
min-trace-logs = [
    "tracing/release_max_level_trace",
    "hanzo-evm-ethereum-cli/min-trace-logs",
    "hanzo-evm-node-core/min-trace-logs",
]

rocksdb = ["hanzo-evm-ethereum-cli/rocksdb", "hanzo-evm-node-core/rocksdb"]
edge = ["rocksdb"]

[[bin]]
name = "hanzo-evm"
path = "src/main.rs"
