[package]
name = "hanzo-evm-ethereum-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A basic ethereum payload builder for Hanzo EVM that uses the txpool API to build payloads."

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-consensus-common.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-revm.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-payload-builder-primitives.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-basic-payload-builder.workspace = true
hanzo-evm-execution.workspace = true
hanzo-evm-eth-execution = { workspace = true, features = ["std"] }
hanzo-evm-errors.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-payload-validator.workspace = true

# ethereum
alloy-rlp.workspace = true
alloy-rpc-types-engine.workspace = true
revm.workspace = true

# alloy
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true

# misc
tracing.workspace = true
