[package]
name = "hanzo-evm-ethereum-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Ethereum primitive types"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-codecs = { workspace = true, optional = true }
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-zstd-compressors = { workspace = true, optional = true }

# ethereum
alloy-eips = { workspace = true, features = ["k256"] }
alloy-primitives.workspace = true
alloy-consensus = { workspace = true, features = ["serde"] }
alloy-serde = { workspace = true, optional = true }
alloy-rpc-types-eth = { workspace = true, optional = true }
alloy-rlp.workspace = true

# misc
arbitrary = { workspace = true, optional = true, features = ["derive"] }
modular-bitfield = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }

[dev-dependencies]
derive_more.workspace = true
arbitrary.workspace = true
bincode.workspace = true
proptest.workspace = true
proptest-arbitrary-interop.workspace = true
rand_08.workspace = true
rand.workspace = true
hanzo-evm-codecs = { workspace = true, features = ["test-utils"] }
hanzo-evm-zstd-compressors.workspace = true
secp256k1 = { workspace = true, features = ["rand"] }
alloy-consensus = { workspace = true, features = ["serde", "arbitrary"] }
serde_json.workspace = true

[features]
default = ["std"]
test-utils = [
    "hanzo-evm-codecs?/test-utils",
    "hanzo-evm-primitives-traits/test-utils",
]
std = [
    "alloy-consensus/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "hanzo-evm-primitives-traits/std",
    "hanzo-evm-zstd-compressors?/std",
    "serde?/std",
    "alloy-eips/std",
    "derive_more/std",
    "serde_with?/std",
    "secp256k1/std",
    "alloy-rpc-types-eth?/std",
    "alloy-serde?/std",
    "serde_json/std",
]
hanzo-evm-codec = [
    "std",
    "dep:hanzo-evm-codecs",
    "dep:modular-bitfield",
    "dep:hanzo-evm-zstd-compressors",
]
arbitrary = [
    "std",
    "dep:arbitrary",
    "alloy-consensus/arbitrary",
    "alloy-consensus/k256",
    "alloy-primitives/arbitrary",
    "hanzo-evm-codecs?/arbitrary",
    "hanzo-evm-primitives-traits/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-rpc-types-eth?/arbitrary",
    "alloy-serde?/arbitrary",
]
serde-bincode-compat = [
    "dep:serde_with",
    "alloy-consensus/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
    "hanzo-evm-primitives-traits/serde-bincode-compat",
    "alloy-rpc-types-eth?/serde-bincode-compat",
]
serde = [
    "dep:serde",
    "dep:alloy-serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "hanzo-evm-codecs?/serde",
    "hanzo-evm-primitives-traits/serde",
    "rand/serde",
    "rand_08/serde",
    "secp256k1/serde",
    "alloy-rpc-types-eth?/serde",
]
rpc = ["dep:alloy-rpc-types-eth"]
