[package]
name = "hanzo-evm-engine-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-execution.workspace = true
hanzo-evm-execution-types.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-payload-builder-primitives.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-chain-state.workspace = true
hanzo-evm-errors.workspace = true
hanzo-evm-trie-common.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-eips.workspace = true

# async
tokio = { workspace = true, features = ["sync"], optional = true }
futures = { workspace = true, optional = true }

# misc
auto_impl.workspace = true
serde.workspace = true
thiserror.workspace = true

[features]
default = ["std"]
std = [
    "hanzo-evm-execution-types/std",
    "hanzo-evm-ethereum-primitives/std",
    "hanzo-evm-primitives-traits/std",
    "hanzo-evm-trie-common/std",
    "alloy-primitives/std",
    "alloy-consensus/std",
    "alloy-rpc-types-engine/std",
    "alloy-eips/std",
    "futures/std",
    "tokio",
    "serde/std",
    "thiserror/std",
    "hanzo-evm-execution/std",
]
