[package]
name = "hanzo-evm-trie-parallel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Parallel implementation of merkle root algorithm"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives-traits = { workspace = true, features = ["dashmap", "std"] }
reth-execution-errors.workspace = true
reth-provider.workspace = true
reth-storage-errors.workspace = true
reth-trie-sparse = { workspace = true, features = ["std"] }
reth-tasks = { workspace = true, features = ["rayon"] }
reth-trie.workspace = true

# alloy
alloy-rlp.workspace = true
alloy-primitives.workspace = true

# tracing
tracing.workspace = true

# misc
thiserror.workspace = true
derive_more.workspace = true
rayon.workspace = true
itertools.workspace = true
crossbeam-channel.workspace = true

# `metrics` feature
hanzo-evm-metrics = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }

[dev-dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-trie-db.workspace = true
hanzo-evm-trie = { workspace = true, features = ["test-utils"] }

# misc
rand.workspace = true
criterion.workspace = true
proptest.workspace = true
proptest-arbitrary-interop.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }

[features]
default = ["metrics"]
metrics = ["hanzo-evm-metrics", "dep:metrics", "hanzo-evm-trie/metrics", "hanzo-evm-trie-sparse/metrics"]
test-utils = [
    "reth-primitives-traits/test-utils",
    "reth-provider/test-utils",
    "reth-trie-db/test-utils",
    "reth-trie-sparse/test-utils",
    "reth-trie/test-utils",
    "reth-tasks/test-utils",
]

[[bench]]
name = "root"
harness = false
