[package]
name = "hanzo-evm-rpc-e2e-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "RPC end-to-end tests including execution-apis compatibility testing"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-e2e-test-utils.workspace = true
hanzo-evm-rpc-api = { workspace = true, features = ["client"] }

# ethereum
alloy-rpc-types-engine.workspace = true

# async
tokio.workspace = true
futures-util.workspace = true

# misc
eyre.workspace = true
serde_json.workspace = true
tracing.workspace = true
jsonrpsee.workspace = true

# required for the Action trait
hanzo-evm-node-api.workspace = true

[dev-dependencies]
hanzo-evm-tracing.workspace = true
hanzo-evm-chainspec.workspace = true
hanzo-evm-node-ethereum.workspace = true
alloy-genesis.workspace = true

[[test]]
name = "e2e_testsuite"
path = "tests/e2e-testsuite/main.rs"
