[package]
name = "hanzo-evm-rpc-engine-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Implementation of Engine API"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-chainspec.workspace = true
hanzo-evm-rpc-api.workspace = true
hanzo-evm-storage-api.workspace = true
hanzo-evm-payload-builder.workspace = true
hanzo-evm-payload-builder-primitives.workspace = true
hanzo-evm-payload-primitives.workspace = true
hanzo-evm-tasks.workspace = true
hanzo-evm-engine-primitives.workspace = true
hanzo-evm-transaction-pool.workspace = true
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-network-api.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }

# metrics
hanzo-evm-metrics.workspace = true
metrics.workspace = true

# misc
async-trait.workspace = true
jsonrpsee-core.workspace = true
jsonrpsee-types.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
hanzo-evm-ethereum-engine-primitives.workspace = true
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-ethereum-primitives.workspace = true
hanzo-evm-payload-builder = { workspace = true, features = ["test-utils"] }
hanzo-evm-testing-utils.workspace = true
alloy-rlp.workspace = true
reth-node-ethereum.workspace = true
reth-tasks = { workspace = true, features = ["test-utils"] }

assert_matches.workspace = true
