[package]
name = "hanzo-evm-trie-sparse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Sparse MPT implementation"

[lints]
workspace = true

[dependencies]
# evm
hanzo-evm-primitives-traits.workspace = true
hanzo-evm-execution-errors.workspace = true
hanzo-evm-trie-common.workspace = true
tracing = { workspace = true, features = ["attributes"] }
alloy-trie.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# misc
auto_impl.workspace = true
rayon = { workspace = true, optional = true }

# metrics
hanzo-evm-metrics = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }

[dev-dependencies]
hanzo-evm-primitives-traits = { workspace = true, features = ["arbitrary"] }
hanzo-evm-provider = { workspace = true, features = ["test-utils"] }
hanzo-evm-storage-api.workspace = true
hanzo-evm-testing-utils.workspace = true
hanzo-evm-trie = { workspace = true, features = ["test-utils"] }
hanzo-evm-trie-common = { workspace = true, features = ["test-utils", "arbitrary"] }
hanzo-evm-trie-db = { workspace = true, features = ["test-utils"] }
hanzo-evm-tracing.workspace = true

arbitrary.workspace = true
assert_matches.workspace = true
criterion.workspace = true
itertools.workspace = true
pretty_assertions.workspace = true
proptest-arbitrary-interop.workspace = true
proptest.workspace = true
rand.workspace = true
rand_08.workspace = true

[features]
default = ["std", "metrics"]
std = [
    "dep:rayon",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "alloy-trie/std",
    "hanzo-evm-execution-errors/std",
    "hanzo-evm-primitives-traits/std",
    "hanzo-evm-primitives-traits/rayon",
    "hanzo-evm-storage-api/std",
    "hanzo-evm-trie-common/std",
    "tracing/std",
]
metrics = ["dep:hanzo-evm-metrics", "dep:metrics", "std"]
test-utils = [
    "std",
    "hanzo-evm-primitives-traits/test-utils",
    "hanzo-evm-provider/test-utils",
    "hanzo-evm-trie-common/test-utils",
    "hanzo-evm-trie-db/test-utils",
    "hanzo-evm-trie/test-utils",
]
arbitrary = [
    "std",
    "alloy-primitives/arbitrary",
    "alloy-trie/arbitrary",
    "hanzo-evm-primitives-traits/arbitrary",
    "hanzo-evm-trie-common/arbitrary",
]

[[bench]]
name = "root"
harness = false

[[bench]]
name = "rlp_node"
harness = false
